submit : UserClient.pl testbench.csh stub.pl

	cp UserClient.pl submit
	chmod u+x submit

	cp testbench.csh testbench
	chmod u+x testbench

	cp stub.pl testservserofDOOM
	chmod u+x testservserofDOOM

	cp stub2.pl stub2
	chmod u+x stub2

clean :
	rm submit
	rm testbench
	rm testservserofDOOM
	rm stub2
