main: Session-Token-0.82.tar.gz
	tar -xf Session-Token-0.82.tar.gz
	cd Session-Token-0.82 ; perl Makefile.PL ; make 
	cd .. ; cd .. ; rm -rf students; mkdir students
	rm -rf Session-Token-0.82.tar.gz
